# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'five_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StatisticsWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(400, 450)
        mainWindow.setStyleSheet("background-color: rgb(33, 81, 255);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(20, 19, 71, 31))
        self.exit_button.setStyleSheet("QPushButton {\n"
"    background-color: #ff0004;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 15px;  \n"
"     \n"
"    font-weight: bold;  \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #9a0002;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #700001;\n"
"}")
        self.exit_button.setObjectName("exit_button")
        self.statistics_label = QtWidgets.QLabel(self.centralwidget)
        self.statistics_label.setGeometry(QtCore.QRect(110, 10, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.statistics_label.setFont(font)
        self.statistics_label.setStyleSheet("QLabel {\n"
"        color: rgb(33, 81, 255);\n"
"      \n"
"        border-radius: 15px;     \n"
"        padding: 5px;              \n"
"        background-color: rgb(245, 246, 250);\n"
"     }\n"
"\n"
"\n"
"\n"
"")
        self.statistics_label.setAlignment(QtCore.Qt.AlignCenter)
        self.statistics_label.setObjectName("statistics_label")
        self.reset_statistics_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_statistics_button.setGeometry(QtCore.QRect(210, 410, 181, 31))
        self.reset_statistics_button.setStyleSheet("QPushButton {\n"
"    background-color: #ff0004;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 15px;  \n"
"     \n"
"    font-weight: bold;  \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #9a0002;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #700001;\n"
"}")
        self.reset_statistics_button.setObjectName("reset_statistics_button")
        self.counter_right_answer_label = QtWidgets.QLabel(self.centralwidget)
        self.counter_right_answer_label.setGeometry(QtCore.QRect(220, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.counter_right_answer_label.setFont(font)
        self.counter_right_answer_label.setStyleSheet("QLabel {\n"
"        color: rgb(33, 81, 255);\n"
"      \n"
"        border-radius: 15px;     \n"
"        padding: 5px;              \n"
"        background-color: rgb(245, 246, 250);\n"
"     }\n"
"\n"
"\n"
"\n"
"")
        self.counter_right_answer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.counter_right_answer_label.setObjectName("counter_right_answer_label")
        self.count_no_rights_answer_label = QtWidgets.QLabel(self.centralwidget)
        self.count_no_rights_answer_label.setGeometry(QtCore.QRect(220, 140, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.count_no_rights_answer_label.setFont(font)
        self.count_no_rights_answer_label.setStyleSheet("QLabel {\n"
"        color: rgb(33, 81, 255);\n"
"      \n"
"        border-radius: 15px;     \n"
"        padding: 5px;              \n"
"        background-color: rgb(245, 246, 250);\n"
"     }\n"
"\n"
"\n"
"\n"
"")
        self.count_no_rights_answer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.count_no_rights_answer_label.setObjectName("count_no_rights_answer_label")
        self.count_all_answer_label = QtWidgets.QLabel(self.centralwidget)
        self.count_all_answer_label.setGeometry(QtCore.QRect(220, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.count_all_answer_label.setFont(font)
        self.count_all_answer_label.setStyleSheet("QLabel {\n"
"        color: rgb(33, 81, 255);\n"
"      \n"
"        border-radius: 15px;     \n"
"        padding: 5px;              \n"
"        background-color: rgb(245, 246, 250);\n"
"     }\n"
"\n"
"\n"
"\n"
"")
        self.count_all_answer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.count_all_answer_label.setObjectName("count_all_answer_label")
        self.right_answer_label = QtWidgets.QLabel(self.centralwidget)
        self.right_answer_label.setGeometry(QtCore.QRect(30, 80, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.right_answer_label.setFont(font)
        self.right_answer_label.setStyleSheet("QLabel {\n"
"        \n"
"        color: rgb(244, 244, 251);\n"
"       \n"
"        background-color: #1bff0f;\n"
"        border-radius: 15px;     \n"
"        padding: 5px;              \n"
"        \n"
"     }\n"
"\n"
"\n"
"\n"
"")
        self.right_answer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.right_answer_label.setObjectName("right_answer_label")
        self.all_answer_label = QtWidgets.QLabel(self.centralwidget)
        self.all_answer_label.setGeometry(QtCore.QRect(30, 200, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.all_answer_label.setFont(font)
        self.all_answer_label.setStyleSheet("QLabel {\n"
"        color: #F4F4FB;\n"
"      \n"
"        border-radius: 15px;     \n"
"        padding: 5px;              \n"
"        background-color: #39AFEA;\n"
"     }\n"
"\n"
"\n"
"\n"
"")
        self.all_answer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.all_answer_label.setObjectName("all_answer_label")
        self.no_right_answer_label = QtWidgets.QLabel(self.centralwidget)
        self.no_right_answer_label.setGeometry(QtCore.QRect(30, 140, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.no_right_answer_label.setFont(font)
        self.no_right_answer_label.setStyleSheet("QLabel {\n"
"        color: #F4F4FB;\n"
"      \n"
"        border-radius: 15px;     \n"
"        padding: 5px;              \n"
"         background-color: #ff0004;\n"
"     }\n"
"\n"
"\n"
"\n"
"")
        self.no_right_answer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.no_right_answer_label.setObjectName("no_right_answer_label")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Memory cards"))
        self.exit_button.setText(_translate("mainWindow", "выход"))
        self.statistics_label.setText(_translate("mainWindow", "Статистика"))
        self.reset_statistics_button.setText(_translate("mainWindow", "Сбросить статистику"))
        self.counter_right_answer_label.setText(_translate("mainWindow", "0"))
        self.count_no_rights_answer_label.setText(_translate("mainWindow", "0"))
        self.count_all_answer_label.setText(_translate("mainWindow", "0"))
        self.right_answer_label.setText(_translate("mainWindow", "Правильных ответов"))
        self.all_answer_label.setText(_translate("mainWindow", "Всего ответов"))
        self.no_right_answer_label.setText(_translate("mainWindow", "Неправильных ответов"))
