# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'four_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListCardsWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(400, 450)
        mainWindow.setStyleSheet("background-color: rgb(33, 81, 255);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(20, 19, 71, 31))
        self.exit_button.setStyleSheet("QPushButton {\n"
"    background-color: #ff0004;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 15px;  \n"
"     \n"
"    font-weight: bold;  \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #9a0002;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #700001;\n"
"}")
        self.exit_button.setObjectName("exit_button")
        self.load_button = QtWidgets.QPushButton(self.centralwidget)
        self.load_button.setGeometry(QtCore.QRect(19, 410, 111, 30))
        self.load_button.setStyleSheet("QPushButton {\n"
"    background-color: #1aff3c;\n"
"    background-color: rgb(41, 255, 26);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 15px;  \n"
"\n"
"    font-weight: bold;  \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #17ab17;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1d861d;\n"
"}")
        self.load_button.setObjectName("load_button")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(140, 410, 111, 31))
        self.save_button.setStyleSheet("QPushButton {\n"
"    background-color: #39AFEA;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 15px;  \n"
"\n"
"    font-weight: bold;  \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #277aa3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #184f68;\n"
"}")
        self.save_button.setObjectName("save_button")
        self.list_cards_label = QtWidgets.QLabel(self.centralwidget)
        self.list_cards_label.setGeometry(QtCore.QRect(110, 10, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.list_cards_label.setFont(font)
        self.list_cards_label.setStyleSheet("QLabel {\n"
"        color: rgb(33, 81, 255);\n"
"      \n"
"        border-radius: 15px;     \n"
"        padding: 5px;              \n"
"        background-color: rgb(245, 246, 250);\n"
"     }\n"
"\n"
"\n"
"\n"
"")
        self.list_cards_label.setAlignment(QtCore.Qt.AlignCenter)
        self.list_cards_label.setObjectName("list_cards_label")
        self.delite_button = QtWidgets.QPushButton(self.centralwidget)
        self.delite_button.setGeometry(QtCore.QRect(260, 410, 121, 31))
        self.delite_button.setStyleSheet("QPushButton {\n"
"    background-color: #ff0004;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 15px;  \n"
"     \n"
"    font-weight: bold;  \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #9a0002;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #700001;\n"
"}")
        self.delite_button.setObjectName("delite_button")
        self.list_all_cards_listwidget = QtWidgets.QListWidget(self.centralwidget)
        self.list_all_cards_listwidget.setGeometry(QtCore.QRect(15, 70, 371, 321))
        self.list_all_cards_listwidget.setStyleSheet("background-color: rgb(244, 244, 251);")
        self.list_all_cards_listwidget.setObjectName("list_all_cards_listwidget")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Memory cards"))
        self.exit_button.setText(_translate("mainWindow", "выход"))
        self.load_button.setText(_translate("mainWindow", "Загрузить"))
        self.save_button.setText(_translate("mainWindow", "Сохранить"))
        self.list_cards_label.setText(_translate("mainWindow", "Список карточек"))
        self.delite_button.setText(_translate("mainWindow", "Удалить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
