# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'one_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(400, 450)
        mainWindow.setStyleSheet("background-color: rgb(33, 81, 255);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.memory_cards_label = QtWidgets.QLabel(self.centralwidget)
        self.memory_cards_label.setGeometry(QtCore.QRect(90, 30, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.memory_cards_label.setFont(font)
        self.memory_cards_label.setStyleSheet("QLabel {\n"
"        color: rgb(33, 81, 255);\n"
"      \n"
"        border-radius: 15px;     \n"
"        padding: 5px;              \n"
"        background-color: rgb(245, 246, 250);\n"
"     }\n"
"\n"
"\n"
"\n"
"")
        self.memory_cards_label.setAlignment(QtCore.Qt.AlignCenter)
        self.memory_cards_label.setObjectName("memory_cards_label")
        self.training_button = QtWidgets.QPushButton(self.centralwidget)
        self.training_button.setGeometry(QtCore.QRect(90, 150, 221, 51))
        self.training_button.setStyleSheet(" QPushButton {\n"
"       background-color: #0079EB;  \n"
"       color: white;                \n"
"       border: none;                \n"
"       border-radius: 15px;         \n"
"       padding: 10px 20px;          \n"
"       text-align: center;      \n"
"       font-size: 20px;       \n"
"       font-weight: bold;\n"
"   }\n"
"\n"
"   QPushButton:hover {\n"
"       background-color: #0067c1;  \n"
"   }\n"
"\n"
"   QPushButton:pressed {\n"
"       background-color: #004884; \n"
"\n"
"   }\n"
"")
        self.training_button.setObjectName("training_button")
        self.creat_cards_button = QtWidgets.QPushButton(self.centralwidget)
        self.creat_cards_button.setGeometry(QtCore.QRect(90, 240, 221, 51))
        self.creat_cards_button.setStyleSheet(" QPushButton {\n"
"       background-color: #0079EB;  \n"
"       color: white;                \n"
"       border: none;                \n"
"       border-radius: 15px;         \n"
"       padding: 10px 20px;          \n"
"       text-align: center;      \n"
"       font-size: 20px;       \n"
"       font-weight: bold;\n"
"   }\n"
"\n"
"   QPushButton:hover {\n"
"       background-color: #0067c1;  \n"
"   }\n"
"\n"
"   QPushButton:pressed {\n"
"       background-color: #004884; \n"
"\n"
"   }\n"
"")
        self.creat_cards_button.setObjectName("creat_cards_button")
        self.statistics_button = QtWidgets.QPushButton(self.centralwidget)
        self.statistics_button.setGeometry(QtCore.QRect(90, 330, 221, 51))
        self.statistics_button.setStyleSheet(" QPushButton {\n"
"       background-color: #0079EB;  \n"
"       color: white;                \n"
"       border: none;                \n"
"       border-radius: 15px;         \n"
"       padding: 10px 20px;          \n"
"       text-align: center;      \n"
"       font-size: 20px;       \n"
"       font-weight: bold;\n"
"   }\n"
"\n"
"   QPushButton:hover {\n"
"       background-color: #0067c1;  \n"
"   }\n"
"\n"
"   QPushButton:pressed {\n"
"       background-color: #004884; \n"
"\n"
"   }\n"
"")
        self.statistics_button.setObjectName("statistics_button")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Memory cards"))
        self.memory_cards_label.setText(_translate("mainWindow", "Memory cards"))
        self.training_button.setText(_translate("mainWindow", "Тренировка"))
        self.creat_cards_button.setText(_translate("mainWindow", "Создать карточки"))
        self.statistics_button.setText(_translate("mainWindow", "Статистика"))
