# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'three_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreatCardsWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(400, 450)
        mainWindow.setStyleSheet("background-color: rgb(33, 81, 255);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(20, 19, 71, 31))
        self.exit_button.setStyleSheet("QPushButton {\n"
"    background-color: #ff0004;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 15px;  \n"
"     \n"
"    font-weight: bold;  \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #9a0002;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #700001;\n"
"}")
        self.exit_button.setObjectName("exit_button")
        self.add_card_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_card_button.setGeometry(QtCore.QRect(19, 410, 141, 30))
        self.add_card_button.setStyleSheet("QPushButton {\n"
"    background-color: #1aff3c;\n"
"    background-color: rgb(41, 255, 26);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 15px;  \n"
"\n"
"    font-weight: bold;  \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #17ab17;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1d861d;\n"
"}")
        self.add_card_button.setObjectName("add_card_button")
        self.list_cards_button = QtWidgets.QPushButton(self.centralwidget)
        self.list_cards_button.setGeometry(QtCore.QRect(230, 410, 151, 31))
        self.list_cards_button.setStyleSheet("QPushButton {\n"
"    background-color: #39AFEA;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 15px;  \n"
"\n"
"    font-weight: bold;  \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #277aa3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #184f68;\n"
"}")
        self.list_cards_button.setObjectName("list_cards_button")
        self.input_question_label = QtWidgets.QLabel(self.centralwidget)
        self.input_question_label.setGeometry(QtCore.QRect(110, 10, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.input_question_label.setFont(font)
        self.input_question_label.setStyleSheet("QLabel {\n"
"        color: rgb(33, 81, 255);\n"
"      \n"
"        border-radius: 15px;     \n"
"        padding: 5px;              \n"
"        background-color: rgb(245, 246, 250);\n"
"     }\n"
"\n"
"\n"
"\n"
"")
        self.input_question_label.setAlignment(QtCore.Qt.AlignCenter)
        self.input_question_label.setObjectName("input_question_label")
        self.input_answer_label = QtWidgets.QLabel(self.centralwidget)
        self.input_answer_label.setGeometry(QtCore.QRect(110, 190, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.input_answer_label.setFont(font)
        self.input_answer_label.setStyleSheet("QLabel {\n"
"        color: rgb(33, 81, 255);\n"
"      \n"
"        border-radius: 15px;     \n"
"        padding: 5px;              \n"
"        background-color: rgb(245, 246, 250);\n"
"     }\n"
"\n"
"\n"
"\n"
"")
        self.input_answer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.input_answer_label.setObjectName("input_answer_label")
        self.input_answer_text = QtWidgets.QTextEdit(self.centralwidget)
        self.input_answer_text.setGeometry(QtCore.QRect(20, 240, 361, 161))
        self.input_answer_text.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid #2196F3; \n"
"padding: 5px;             ")
        self.input_answer_text.setObjectName("input_answer_text")
        self.input_question_text = QtWidgets.QTextEdit(self.centralwidget)
        self.input_question_text.setGeometry(QtCore.QRect(20, 60, 361, 121))
        self.input_question_text.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid #2196F3; \n"
"padding: 5px;             ")
        self.input_question_text.setObjectName("input_question_text")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Memory cards"))
        self.exit_button.setText(_translate("mainWindow", "выход"))
        self.add_card_button.setText(_translate("mainWindow", "Добавить карточку"))
        self.list_cards_button.setText(_translate("mainWindow", "Список карточек"))
        self.input_question_label.setText(_translate("mainWindow", "Введите вопрос"))
        self.input_answer_label.setText(_translate("mainWindow", "Введите ответ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
