# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'two_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TrainingWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(400, 450)
        mainWindow.setStyleSheet("background-color: rgb(33, 81, 255);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.training_label = QtWidgets.QLabel(self.centralwidget)
        self.training_label.setGeometry(QtCore.QRect(110, 10, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.training_label.setFont(font)
        self.training_label.setStyleSheet("QLabel {\n"
"        color: rgb(33, 81, 255);\n"
"      \n"
"        border-radius: 15px;     \n"
"        padding: 5px;              \n"
"        background-color: rgb(245, 246, 250);\n"
"     }\n"
"\n"
"\n"
"\n"
"")
        self.training_label.setAlignment(QtCore.Qt.AlignCenter)
        self.training_label.setObjectName("training_label")
        self.answer_label = QtWidgets.QTextBrowser(self.centralwidget)
        self.answer_label.setGeometry(QtCore.QRect(20, 210, 361, 181))
        self.answer_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid #2196F3; \n"
"padding: 5px;             ")
        self.answer_label.setObjectName("input_answer_text")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(20, 19, 71, 31))
        self.exit_button.setStyleSheet("QPushButton {\n"
"    background-color: #ff0004;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 15px;  \n"
"     \n"
"    font-weight: bold;  \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #9a0002;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #700001;\n"
"}")
        self.exit_button.setObjectName("exit_button")
        self.question_label = QtWidgets.QLabel(self.centralwidget)
        self.question_label.setGeometry(QtCore.QRect(40, 70, 321, 121))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.question_label.setFont(font)
        self.question_label.setStyleSheet("\n"
" border: 2px solid #2196F3;  \n"
" border-radius: 15px;      \n"
"padding: 5px;              \n"
"background-color: white;\n"
"")
        self.question_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.question_label.setObjectName("question_label")
        self.not_right_button = QtWidgets.QPushButton(self.centralwidget)
        self.not_right_button.setGeometry(QtCore.QRect(279, 410, 101, 30))
        self.not_right_button.setStyleSheet("QPushButton {\n"
"    background-color: #ff0004;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 15px;  \n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #9a0002;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #700001;\n"
"}")
        self.not_right_button.setObjectName("not_right_button")
        self.right_button = QtWidgets.QPushButton(self.centralwidget)
        self.right_button.setGeometry(QtCore.QRect(19, 410, 101, 30))
        self.right_button.setStyleSheet("QPushButton {\n"
"    background-color: #1aff3c;\n"
"    background-color: rgb(41, 255, 26);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 15px;  \n"
"\n"
"    font-weight: bold;  \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #17ab17;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1d861d;\n"
"}")
        self.right_button.setObjectName("right_button")
        self.show_answer_button = QtWidgets.QPushButton(self.centralwidget)
        self.show_answer_button.setGeometry(QtCore.QRect(130, 410, 141, 31))
        self.show_answer_button.setStyleSheet("QPushButton {\n"
"    background-color: #39AFEA;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 15px;  \n"
"\n"
"    font-weight: bold;  \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #277aa3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #184f68;\n"
"}")
        self.show_answer_button.setObjectName("show_answer_button")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Memory cards"))
        self.training_label.setText(_translate("mainWindow", "Тренировка"))
        self.answer_label.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>"))
        self.exit_button.setText(_translate("mainWindow", "выход"))
        self.question_label.setText(_translate("mainWindow", ""))
        self.not_right_button.setText(_translate("mainWindow", "Неправильно"))
        self.right_button.setText(_translate("mainWindow", "Правильно"))
        self.show_answer_button.setText(_translate("mainWindow", "Показать ответ"))
